// export { default as ContactsModule } from "./ContactsModule";
export { default as FallbackModule } from "./FallbackModule.jsx";
// export { default as FeedbackModule } from "./FeedbackModule";
// export { default as FileslistModule } from "./FileslistModule";
// export { default as GalleryModule } from "./GalleryModule";
// export { default as IframeModule } from "./IframeModule";
export { default as ImageModule } from "./ImageModule.jsx";
// export { default as MenuModule } from "./MenuModule";
// export { default as NoticeModule } from "./NoticeModule";
export { default as PostsModule } from "./PostsModule.jsx";
// export { default as TableModule } from "./TableModule";
export { default as TextModule } from "./TextModule.jsx";
// export { default as VideoModule } from "./VideoModule";
