root: true
plugins:
  - react
extends:
  - eslint:recommended
  - plugin:react/recommended
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: "17"
env:
  browser: true
  es6: true
  node: true
